#!/bin/sh
# output volume % (or mute), and update when volume changes
# depends on inotifywait from inotify-tools

snd_dev="/dev/snd/controlC0"

output_vol() {  # {{{
  list_sinks=$(pacmd list-sinks)
  sink=$(echo "$list_sinks" | egrep -x -m 1 "[[:space:]]*\*\ index:\ [0-9]+" \
    | grep -o "[0-9]*$")
  sink_details=$(echo "$list_sinks" \
    | sed -e "/^[[:space:]]*\* index: ${sink}$/,/^\ *index/!d")
  cur_vol=$(echo "$sink_details" \
    | egrep -m 1 "^[[:space:]]*volume:" | egrep -o "[0-9]{1,3}%" | head -n 1)
  muted=$(echo "$sink_details" | egrep -m 1 "^[[:space:]]*muted:" \
    | egrep -o "(yes|no)$")

  if [ "$muted" = "yes" ]; then
    echo "MUTE"
  else
    echo "$cur_vol"
  fi
}   # }}}

while [ -x /usr/bin/inotifywait ]; do
  output_vol
  # wait for someone to access the sound card...
  inotifywait --quiet -e access -e close_write "$snd_dev" > /dev/null 2>&1
done
