#!/bin/sh
# attach or create a tmux session running vim (suppress status bar, too)

term_cmd="kitty --name SP-vim"
# term_cmd="xterm -name SP-vim"

if tmux has-session -t notes 2> /dev/null; then
  $term_cmd -e tmux attach-session -t notes
else
  $term_cmd -e tmux new-session -s notes 'vim ~/notes' \
    \; set-option status off
fi
