#!/bin/sh
# fix various devices
# Usage: fix-it [mouse|cellular]

usage() { # {{{
cat <<EOF
Usage: fix-it [mouse|cellular]
EOF
}  # }}}
echo_sleep() { # {{{
  echo "Sleeping $1s" && sleep $1
}  # }}}

case $1 in
  "mouse")    
    sudo modprobe -r psmouse && sudo modprobe psmouse \
      && echo_sleep 5 && && trackpoint-setup
  ;;
  "cellular") 
    sudo modprobe -r cdc_mbim && sudo modprobe cdc_mbim \
      && echo_sleep 15 && sudo systemctl restart ModemManager.service
  ;;
  *) usage() ;;
esac
