#!/bin/sh
# fzf interface to surfraw

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --bind=enter:replace-query+print-query --prompt='Surfraw: '"
default_elvi="duckduckgo"
cache_file="$HOME/.binrc/fzf-surfraw_cache"
custom_file="$HOME/.binrc/fzf-surfraw_custom"

name=$( basename "$0" )
fifo_name=/tmp/${name}_${USER}

# Update the list of elvis (first 2 lines aren't usable). Add a space at the
# end of each line so that completion is nicer.
surfraw -elvi | tail --lines=+3 | awk '{print $1" "}' > $cache_file

while true; do
  query=$( cat $cache_file $custom_file | fzf )

  # signal the caller that we can go back to the scratch workspace
  [ -p $fifo_name ] && echo 1 > $fifo_name || exit

  # If query is non-empty then search for it it.
  if [ -n "$query" ]; then
    # If we don't see the first word as an elvi, then use duckduckgo. Note the
    # space in the awk command!
    if [ -z $(grep -x "$(echo "$query" | awk '{print $1" "}')" $cache_file) ]; then
      query="$default_elvi $query"
    fi

    # run surfraw
    setsid surfraw $query 1>/dev/null 2>&1
  fi

done
